name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  tags:
    - *

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Cache homebrew
      id: cache
      uses: actions/cache@v2
      with:
         path: |
           /usr/local/
         key: ${{ runner.os }}-${{ hashFiles('**/go.yml') }} # Hash based on this file

    - name: Install Brews
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        brew install protobuf protoc-gen-go protoc-gen-go-grpc fswatch
        brew install go || true
        brew link --overwrite go

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: ${{ github.ref == 'refs/tags/' }}
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_BREW_TOKEN: ${{ secrets.GH_BREW_TOKEN }}
