name: TODOs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v3.0.5"
      id: "todo"
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
